// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package feeddb

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type FeedInboxEvent struct {
	EventID       uuid.UUID          `json:"event_id"`
	SourceService string             `json:"source_service"`
	EventType     string             `json:"event_type"`
	AggregateType pgtype.Text        `json:"aggregate_type"`
	AggregateID   pgtype.Text        `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
	LastError     pgtype.Text        `json:"last_error"`
}

type FeedRecommendationLog struct {
	LogID                   uuid.UUID          `json:"log_id"`
	UserID                  pgtype.Text        `json:"user_id"`
	RequestLimit            int32              `json:"request_limit"`
	RecommendationSource    string             `json:"recommendation_source"`
	RecommendationLatencyMs pgtype.Int4        `json:"recommendation_latency_ms"`
	RecommendedItems        []byte             `json:"recommended_items"`
	MissingVideoIds         []byte             `json:"missing_video_ids"`
	ErrorKind               pgtype.Text        `json:"error_kind"`
	GeneratedAt             pgtype.Timestamptz `json:"generated_at"`
}

type FeedVideosProjection struct {
	VideoID           uuid.UUID          `json:"video_id"`
	Title             string             `json:"title"`
	Description       pgtype.Text        `json:"description"`
	DurationMicros    pgtype.Int8        `json:"duration_micros"`
	ThumbnailUrl      pgtype.Text        `json:"thumbnail_url"`
	HlsMasterPlaylist pgtype.Text        `json:"hls_master_playlist"`
	Status            pgtype.Text        `json:"status"`
	VisibilityStatus  pgtype.Text        `json:"visibility_status"`
	PublishedAt       pgtype.Timestamptz `json:"published_at"`
	Version           int64              `json:"version"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
