// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/bionicotaku/lingo-services-feed/internal/controllers"
	"github.com/bionicotaku/lingo-services-feed/internal/infrastructure/configloader"
	"github.com/bionicotaku/lingo-services-feed/internal/infrastructure/grpc_server"
	"github.com/bionicotaku/lingo-services-feed/internal/repositories"
	"github.com/bionicotaku/lingo-services-feed/internal/services"
	"github.com/bionicotaku/lingo-utils/gcjwt"
	"github.com/bionicotaku/lingo-utils/gclog"
	"github.com/bionicotaku/lingo-utils/observability"
	"github.com/bionicotaku/lingo-utils/pgxpoolx"
	"github.com/go-kratos/kratos/v2"
	"github.com/google/wire"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp 构建整个 Kratos 应用，分阶段装配依赖。
//
// Wire 会根据类型自动解析依赖关系并生成 wire_gen.go，详细的 Provider 列表见文件末尾注释。
//
// 依赖注入顺序:
//  1. 配置加载: configloader.ProviderSet 解析配置并派生组件配置
//  2. 基础设施: gclog → observability → gcjwt → pgxpoolx → txmanager
//  3. 业务层: repositories → services → controllers
//  4. 服务器: grpc_server.ProviderSet 组装 gRPC Server
//  5. 应用: newApp 创建 Kratos App
func wireApp(contextContext context.Context, params configloader.Params) (*kratos.App, func(), error) {
	runtimeConfig, err := configloader.LoadRuntimeConfig(params)
	if err != nil {
		return nil, nil, err
	}
	observabilityConfig := configloader.ProvideObservabilityConfig(runtimeConfig)
	serviceInfo := configloader.ProvideServiceInfo(runtimeConfig)
	observabilityServiceInfo := configloader.ProvideObservabilityInfo(serviceInfo)
	config := configloader.ProvideLoggerConfig(serviceInfo)
	component, cleanup, err := gclog.NewComponent(config)
	if err != nil {
		return nil, nil, err
	}
	logger := gclog.ProvideLogger(component)
	observabilityComponent, cleanup2, err := observability.NewComponent(contextContext, observabilityConfig, observabilityServiceInfo, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	serverConfig := configloader.ProvideServerConfig(runtimeConfig)
	metricsConfig := observability.ProvideMetricsConfig(observabilityConfig)
	gcjwtConfig := configloader.ProvideJWTConfig(runtimeConfig)
	gcjwtComponent, cleanup3, err := gcjwt.NewComponent(gcjwtConfig, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	serverMiddleware, err := gcjwt.ProvideServerMiddleware(gcjwtComponent)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	databaseConfig := configloader.ProvideDatabaseConfig(runtimeConfig)
	pgxpoolxConfig := configloader.ProvidePgxConfig(databaseConfig)
	pgxpoolxComponent, cleanup4, err := pgxpoolx.ProvideComponent(contextContext, pgxpoolxConfig, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pool := pgxpoolx.ProvidePool(pgxpoolxComponent)
	feedVideoProjectionRepository := repositories.NewFeedVideoProjectionRepository(pool, logger)
	mockRecommendationProvider := services.NewMockRecommendationProvider(feedVideoProjectionRepository, logger)
	feedService := services.NewFeedService(mockRecommendationProvider, feedVideoProjectionRepository, logger)
	handlerTimeouts := configloader.ProvideHandlerTimeouts(runtimeConfig)
	baseHandler := controllers.NewBaseHandler(handlerTimeouts)
	feedHandler := controllers.NewFeedHandler(feedService, baseHandler, logger)
	server := grpcserver.NewGRPCServer(serverConfig, metricsConfig, serverMiddleware, feedHandler, logger)
	app := newApp(observabilityComponent, logger, server, serviceInfo)
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var feedConfigSet = wire.NewSet(configloader.LoadRuntimeConfig, configloader.ProvideServiceInfo, configloader.ProvideLoggerConfig, configloader.ProvideObservabilityConfig, configloader.ProvideObservabilityInfo, configloader.ProvideServerConfig, configloader.ProvideHandlerTimeouts, configloader.ProvideDatabaseConfig, configloader.ProvidePgxConfig, configloader.ProvideTxConfig, configloader.ProvideJWTConfig)
